kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: docker:dind
    commands:
      - mkdir /drone/src/config/prod
      - echo "$JWT_PRIVATE_KEY" > key.base64
      - base64 -d key.base64 > /drone/src/config/prod/key.bin
      - docker build -t partygo-backend --build-arg "SECRET_KEY_BASE=$SECRET_KEY_BASE" .
      - docker save partygo-backend > /drone/src/partygo-backend.tar
    environment:
      JWT_PRIVATE_KEY:
          from_secret: jwt_private_key
      SECRET_KEY_BASE:
          from_secret: phoenix_key
    volumes:
      - name: dockersock
        path: /var/run/docker.sock

  - name: deploy
    image: drillster/drone-rsync
    settings:
      hosts: void.ar
      port: 22
      user: ci
      key:
        from_secret: deploy_key
      target: /usr/local/src/
      source: /drone/src/partygo-backend.tar
      delete: true
      script:
        - sudo docker load < /usr/local/src/partygo-backend.tar
        - sudo systemctl restart partygo-backend

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

trigger:
  branch:
    - main
  event:
    - push

